# Generated by Django 4.0.3 on 2023-10-18 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_historydata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historydata',
            old_name='spacial_balls',
            new_name='special_balls',
        ),
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 17, 57, 19, 733301)),
        ),
    ]
