# Generated by Django 4.2.6 on 2023-10-18 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_rename_spacial_balls_historydata_special_balls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 21, 45, 57, 877610)),
        ),
    ]
