# Generated by Django 4.2.6 on 2023-10-20 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_rename_lottery_id_userfavorite_lottery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterymetadata',
            name='image_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 4, 55, 32, 836257)),
        ),
    ]
