# Generated by Django 4.2.6 on 2023-10-25 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0011_lotterymetadata_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 17, 11, 22, 207700)),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('balls', models.CharField(max_length=256, null=True)),
                ('special_balls', models.CharField(max_length=256, null=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='lottery.lotterymetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
