# Generated by Django 4.2.6 on 2023-10-31 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_alter_historydata_write_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 14, 54, 16, 858241)),
        ),
    ]
