# Generated by Django 4.2.6 on 2023-11-04 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0016_alter_historydata_write_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 23, 40, 4, 85211)),
        ),
        migrations.CreateModel(
            name='LotteryStateMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='lottery.lotterymetadata')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='lottery.state')),
            ],
        ),
    ]
