# Generated by Django 4.2.6 on 2023-10-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.TextField(default='')),
            ],
        ),
    ]
